In [1]:
# Matrix Multiplier
import numpy as np

def computeProductByColumnView(A: np.array, B: np.array) -> np.array:
    # Create new array for storing results
    C = np.zeros((A.shape[0], B.shape[1]))
    # Loop for each column of C
    for i in range(C.shape[1]):
        C[:, i] = A.dot(B[:, i])
    return C

# Verify solution
A = np.array([[1, 4, 7]])
B = np.array([[3], [1], [2]])
print(computeProductByColumnView(A, B))

[[21.]]


In [2]:
#Linear System Solver
import numpy as np

def findInstersectionIfExists(e1: np.array, e2: np.array) -> str:
    alpha = e1[0]/e2[0]
    e2 = e2*alpha
    if (e2==e1).all():
        return "There are infinitely many solutions"
    elif (e2[:2] == e1[:2]).all():
        return "Intersection does not exist"
    else:
        e2 = e2 - e1
        w2 = e2[2]/e2[1]
        w1 = (e1[2]-(e1[1]*w2))/e1[0]
        return '%.3f , %.3f' %(w1,w2)

# Verify solution
e1 = np.array([2, 4, 9])
e2 = np.array([3, 7, 3])
print(findInstersectionIfExists(e1,e2))

25.500 , -10.500


In [3]:
#Linear Combination Checker
import numpy as np

def IsIntLC(A: np.array, B: np.array, C: np.array) -> bool:
    for i in range(-100, 100):
        for j in range(-100, 100):
            if np.sum((i*A+j*B-C)**2)<0.00000001:
                return True
    return False

# Verify solution
A = np.array([[5, 3, 2], [6, 7, 8], [2, 5, 4]])
B = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
C = np.array([[6, 4, 3], [7, 8, 9], [3, 6, 5]])
print(IsIntLC(A, B, C))

True


In [4]:
#Lower-upper Decompostion Algo
import numpy as np
        
def computeLUDecomposition(mat: np.array) -> [np.array, np.array]:
    m, n = mat.shape
    U = mat.copy()
    E = np.eye(n, dtype='d')
    for i in range(n):
        for r in range(i+1, n):
            # Factor f to set current row's ith element to 0
            f = U[r][i]/U[i][i]
            
            # If the element is already zero
            if not f:
                continue

            elem = np.eye(n, dtype='d')
            for c in range(i, n):
                U[r][c] = U[r][c] - U[i][c]*f
                # Generate corresponding elementary matrix
                elem[r][c] = elem[r][c] - elem[i][c]*f
            # Compute elimination matrix
            E = np.dot(elem, E)
            
    # Compute L as inverse of elimination matrix
    L = np.linalg.inv(E)
    return L, U

# Verify solution
mat = np.array([[1, 4, -3], [-2, 8, 5], [3, 4, 7]])
L, U = computeLUDecomposition(mat)
print(f"mat = {mat} \nL = {L} \nU = {U}")

mat = [[ 1  4 -3]
 [-2  8  5]
 [ 3  4  7]] 
L = [[ 1.   0.   0. ]
 [-2.   1.   0. ]
 [ 3.  -0.5  1. ]] 
U = [[ 1  4 -3]
 [ 0 16 -1]
 [ 0  0 15]]


In [5]:
# Sum of squared error calc
import numpy as np

#Function to calculate Sum of Squared Error
def calculateSSE(A: np.array, w: np.array, b: np.array) -> int:
    # Compute d
    d = np.dot(A,w)-b
    # Compute sse
    sse = np.dot(d.T,d)
    # Convert sse from an np.array to an int and return 
    return(int(sse))


# Verify solution
A = np.array([[1 , -2],[3 , 1],[1 , 1]])
w = np.array([[1],[1]])
b = np.array([[9],[5],[8]])
print(f"""A = {A}\nw = {w}\nb = {b})""")
SSE = calculateSSE(A,w,b)
print(f"""Sum of Squared Distances = {SSE}""")


A = [[ 1 -2]
 [ 3  1]
 [ 1  1]]
w = [[1]
 [1]]
b = [[9]
 [5]
 [8]])
Sum of Squared Distances = 137


In [6]:
#Subspace dimension finder
import numpy as np

def smallestSubspaceDimensionFinder(S: np.array) -> int:
    rank = np.linalg.matrix_rank(S)
    return rank

S = np.array([[5, 3, 2, 3, 7],
              [6, 7, 2, 1, 8],
              [5, 3, 2, 3, 7],
              [11, 10, 4, 4, 15]])
print(f"S = {S} \nSmallest subspace is of dimensions: {smallestSubspaceDimensionFinder(S)}")

S = [[ 5  3  2  3  7]
 [ 6  7  2  1  8]
 [ 5  3  2  3  7]
 [11 10  4  4 15]] 
Smallest subspace is of dimensions: 2


In [8]:
# computing eigenvalues and eigenvectors
import numpy as np
from numpy.linalg import eig

A = np.array([[3, 2], [3, 4]], dtype=np.float32)
eigVals, eigVecs = eig(A)
print(f'Eigenvalues of\n{A}\n are\n{eigVals}')
print(f'The corresponding eigenspace-basis vectors are the columns of \n{np.round(eigVecs, 2)}')

Eigenvalues of
[[3. 2.]
 [3. 4.]]
 are
[1. 6.]
The corresponding eigenspace-basis vectors are the columns of 
[[-0.71 -0.55]
 [ 0.71 -0.83]]


In [9]:
# properties of eigenval and eigenvect
import numpy as np
from numpy.linalg import det, eig

A = np.random.rand(3, 3)
eigVals, eigVecs = eig(A)
# Verify product of eigenvalues equals determinant.
print(f'Product of Eigenvalues = {np.prod(eigVals)}')
print(f'Determinant of the matrix = {det(A)}')
# Verify sum of eigenvalues equals trace.
print(f'Sum of Eigenvalues = {np.sum(eigVals)}')
print(f'Trace of the matrix = {np.trace(A)}')

Product of Eigenvalues = -0.01217375931699422
Determinant of the matrix = -0.012173759316994182
Sum of Eigenvalues = 0.7509657055690008
Trace of the matrix = 0.7509657055690017


In [11]:
#Econ SVD
import  numpy as np
from numpy.linalg import svd, matrix_rank as rank

def diag(S, m, n):
    D  = np.zeros((m, n))
    k = len(S)
    D[:k, :k]=np.diag(S)
    return D

def economicSVD(A):
    U, S, Vt = svd(A)
    idx = np.where(S>1e-10)[0]
    U_hat, S_hat, Vt_hat = U[:, idx], S[idx], Vt[idx, :]
    return U_hat, np.diag(S_hat), Vt_hat

m, n = 8, 5
A = np.random.rand(2, n)
A = np.vstack((A, A, A, A)) # to keep the rank smaller we are repeating rows
U, S, Vt = svd(A)
D = diag(S, m, n)
U_hat, D_hat, Vt_hat = economicSVD(A)
print(f'Shapes of U, D and Vt are :', U.shape, D.shape, Vt.shape)
print(f'Shapes of U_hat, D_hat and Vt_hat are :', U_hat.shape, D_hat.shape, Vt_hat.shape)
frobNorm = np.linalg.norm(U.dot(D).dot(Vt)-U_hat.dot(D_hat).dot(Vt_hat))
R = [0, frobNorm]
print(f'The Frobenius norm of UDV^T - hats(UDV^T) is {R[frobNorm>1e-10]}\nRank(A)={rank(A)}')

Shapes of U, D and Vt are : (8, 8) (8, 5) (5, 5)
Shapes of U_hat, D_hat and Vt_hat are : (8, 2) (2, 2) (2, 5)
The Frobenius norm of UDV^T - hats(UDV^T) is 0
Rank(A)=2


C:\Users\zscho\AppData\Local\Temp/ipykernel_3592/2192349198.py:27: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  print(f'The Frobenius norm of UDV^T - hats(UDV^T) is {R[frobNorm>1e-10]}\nRank(A)={rank(A)}')
